language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
- docker build -t skilfulsidiq/udagram-frontend:v1 ./udagram-frontend
- docker build -t skilfulsidiq/reverseproxy:v1 ./udagram-reverseproxy
- docker build -t skilfulsidiq/udagram-api-user:v1 ./udagram-api-user
- docker build -t skilfulsidiq/udagram-api-feed:v1 ./udagram-api-feed


after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push skilfulsidiq/udagram-frontend:v1
- docker push skilfulsidiq/reverseproxy:v1
- docker push skilfulsidiq/udagram-api-user:v1
- docker push skilfulsidiq/udagram-api-feed:v1


