version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: skilfulsidiq/reverseproxy:v6
  backend_user:
    build:
      context: ./udagram-api-user
    image: skilfulsidiq/udagram-api-user:v6
  backend_feed:
    build:
      context: ./udagram-api-feed  
    image: skilfulsidiq/udagram-api-feed:v6
  frontend:
    build:
      context: ./udagram-frontend
      args:
        - BUILD_ENV=development
    image: skilfulsidiq/udagram-frontend:v6