version: "3"

volumes:
  db-data:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - "db-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U udagram"]
      interval: 10s
      timeout: 5s
      retries: 5
  reverseproxy:
      image: skilfulsidiq/udagram-reverseproxy:v2
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: skilfulsidiq/udagram-api-user:v2
    environment:
      POSTGRESS_USERNAME: $POSTGRES_USERNAME
      POSTGRESS_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRESS_DB: $POSTGRES_DB 
      POSTGRESS_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    depends_on:
      - db
  backend-feed:
    image: skilfulsidiq/udagram-api-feed:v2
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: $POSTGRES_USERNAME
      POSTGRESS_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRESS_DB: $POSTGRES_DB 
      POSTGRESS_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    depends_on:
      - db
  frontend:
    image: skilfulsidiq/udagram-frontend:v2
    ports:
      - "8100:80"