version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: skilfulsidiq/udagram-reverseproxy:v1
  backend_user:
    build:
      context: ./udagram-api-user
    image: skilfulsidiq/udagram-api-user:v1
  backend_feed:
    build:
      context: ./udagram-api-feed  
    image: skilfulsidiq/udagram-api-feed:v1
  frontend:
    build:
      context: ./udagram-frontend
      args:
        - BUILD_ENV=development
    image: skilfulsidiq/udagram-frontend:v1