apiVersion: v1
kind: ConfigMap
data:
  AWS_BUCKET: YXJuOmF3czpzMzo6OnNraWxmdWwtdWRhZ3JhbS1idWNrZXQ=  //arn:aws:s3:::skilful-udagram-bucket
  AWS_PROFILE: default
  AWS_REGION: us-east-1
  POSTGRES_DB: ZGF0YWJhc2UtMQ==
  POSTGRESS_HOST: ZGF0YWJhc2UtMS5jYnd0Y3dnb3NmZ3IudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t //database-1.cbwtcwgosfgr.us-east-1.rds.amazonaws.com
  URL: http://localhost:8100
metadata:
  name: env-config