apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-svc
  name: frontend-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-svc
  template:
    metadata:
      labels:
        app: frontend-svc
    spec:
      containers:
        - image: skilfulsidiq/udagram-frontend:v16
          name: frontend-svc
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m" 
          ports:
          - containerPort: 80