apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-user
  name: backend-user
spec:
  selector:
    app: backend-user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080