apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        service: frontend
        api: external        
    spec:
      containers:
      - image: skilfulsidiq/udagram-frontend:v1
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m               
      restartPolicy: Always

